<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\admins;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Tambah akun analis
        admins::create([
                'username' => 'Desi Uli Pasaribu',
                'nama' => 'Desi Uli Pasaribu',
                'email' => 'desi.uli@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'deputi_2',
                'jabatan' => 'Kepala Subbagian Dukungan Administrasi',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Pembangunan Sumber Daya Manusia',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Yudhy Ekomedianov Chandra',
                'nama' => 'Yudhy Ekomedianov Chandra',
                'email' => 'yudhy.ekomedianov@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'deputi_2',
                'jabatan' => 'Kepala Subbagian Dukungan Administrasi',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Ayu Pudianingtias',
                'nama' => 'Ayu Pudianingtias',
                'email' => 'ayu.pudianingtias@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'deputi_1',
                'jabatan' => 'Kepala Subbagian Dukungan Administrasi',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Susi Handayani',
                'nama' => 'Susi Handayani',
                'email' => 'susi.handayani@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'deputi_1',
                'jabatan' => 'Kepala Subbagian Dukungan Administrasi',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Angela Shinta Puspitasari',
                'nama' => 'Angela Shinta Puspitasari',
                'email' => 'angela.shinta@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Ahli Pertama',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Pembangunan Sumber Daya Manusia',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Indira Oktoviani',
                'nama' => 'Indira Oktoviani',
                'email' => 'indira.oktoviani@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Novika Widyasari',
                'nama' => 'Novika Widyasari',
                'email' => 'novika.widyasari@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Sutikno',
                'nama' => 'Sutikno',
                'email' => 'sutikno@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Ahli Madya',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Trisita Ridhawati',
                'nama' => 'Trisita Ridhawati',
                'email' => 'trisita.ridhawati@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Peningkatan Kesejahteraan Dan Pembangunan Sumber Daya Manusia',
                'unit' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Dian Kusumawardani',
                'nama' => 'Dian Kusumawardani',
                'email' => 'dian.kusumawardani@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Pemerintahan dan Pemerataan Pembangunan',
                'unit' => 'Asisten Deputi Tata Kelola Pemerintahan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Donny M. Simanjuntak',
                'nama' => 'Donny M. Simanjuntak',
                'email' => 'donny.simanjuntak@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Rahma Dewi',
                'nama' => 'Rahma Dewi',
                'email' => 'rahma.dewi@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Rahmelya Oktari',
                'nama' => 'Rahmelya Oktari',
                'email' => 'rahmelya.oktari@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Sri Komsiyatun',
                'nama' => 'Sri Komsiyatun',
                'email' => 'sri.komsiyatun@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Madya',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Wibowo Aji Utomo',
                'nama' => 'Wibowo Aji Utomo',
                'email' => 'wibowo.aji@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Adella Bachtiar',
                'nama' => 'Adella Bachtiar',
                'email' => 'adella.bachtiar@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Madya',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Amelia Irna Mayarni Sitohang',
                'nama' => 'Amelia Irna Mayarni Sitohang',
                'email' => 'amelia.irna@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Tata Usaha',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Gito Kuncoro',
                'nama' => 'Gito Kuncoro',
                'email' => 'gito.kuncoro@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Ronny Dwi Caisario',
                'nama' => 'Ronny Dwi Caisario',
                'email' => 'ronny.caisario@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Muda',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        admins::create([
                'username' => 'Thetanaya',
                'nama' => 'Thetanaya',
                'email' => 'thetanaya@set.wapresri.go.id',
                'password' => Hash::make('SETwapres@2024#'),
                'country' => 'Indonesia',
                'phone' => '081234567890',
                'born' => '2024-11-11',
                'avatar' => 'sample-images.png',
                'address' => 'Jl. Kebon Sirih 14, Jakarta',
                'role' => 'analis',
                'jabatan' => 'Analis Kebijakan Madya',
                'deputi' => 'Deputi Bidang Dukungan Kebijakan Perekonomian, Pariwisata, dan Transformasi Digital',
                'unit' => 'Asisten Deputi Ekonomi dan Keuangan',
                'created_at' => now(),
                'updated_at' => now(),
        ]);
    }
}
